version: 2.1
default_steps: &default_steps
  steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: yarn
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn test

jobs:
  test:
    docker:
      - image: circleci/node:12-browsers
    environment:
      PERCY_ENABLE: 0
    <<: *default_steps
  test_percy:
    # We've opted this node version to be the one that runs and reports Percy's status
    docker:
      - image: circleci/node:10-browsers
    <<: *default_steps

workflows:
  version: 2
  test:
    jobs:
      - test
      - test_percy
